@list:
   just --list

# TODO: just db which runs a docker-compose which starts both local-dynamodb and local-postgres

# Start local Dynamodb emulator.
@dynamodb:
    cd dynamodb && ./run-docker-compose.sh

# Start local PostgreSQL database.
@postgres:
    cd postgres && ./run-docker-compose.sh

# Start local Datomic database.
@datomic:
    cd datomic && ./start-datomic.sh

# Reset Datomic SimpleServer databases.
@datomic-ss-reset:
    cd datomic && ./reset-simpleserver-db.sh

# Start Datomic Peer Server. NOTE: NOT NEEDED IN THIS EXERCISE!
@datomic-peer-server:
    cd datomic && ./start-peer-server.sh

# Start Datomic Console.
@datomic-console:
    cd datomic && ./start-console.sh

# Start backend repl.
@backend:
    clj -M:dev:test:common:backend:postgres -m nrepl.cmdline -i -C

# Start backend repl with my toolbox.
@backend-kari:
    clj -M:dev:test:common:backend:postgres:kari -m nrepl.cmdline -i -C

# Start backend repl with my toolbox and with debug-repl capability.
@backend-debug-kari:
    clj -M:dev:test:common:backend:kari -m nrepl.cmdline --middleware com.gfredericks.debug-repl/wrap-debug-repl -i -C

@backend-kari-all:
    clj -M:dev:test:common:backend:kari:reveal -e "(require '[com.gfredericks.debug-repl] '[hashp.core] )" -m nrepl.cmdline --middleware '[com.gfredericks.debug-repl/wrap-debug-repl vlaaad.reveal.nrepl/middleware]' -i -C

# Init node packages.
@init:
   mkdir -p target
   mkdir -p classes
   npm install

# start frontend auto-compilation
@frontend:
    npm run dev

# SASS auto-compile
@css:
    npm run build:sass

# Start frontend auto-compilation.
# @frontend-kari:
#   clj -M:dev:common:frontend:kari -m shadow.cljs.devtools.cli watch app

# SASS auto-compile.
# @css:
# 	clj -Mcss --auto

# Update dependencies.
@outdated:
    clj -M:dev:test:common:backend:frontend:outdated --update

# Create uberjar.
@uberjar:
    npm run build:sass
    mkdir -p prod-resources/public/js
    mkdir -p prod-resources/public/css
    cp dev-resources/public/js/main.js prod-resources/public/js/main.js
    cp dev-resources/public/css/style.css prod-resources/public/css/style.css
    clj -M:uberjar:dev:common:backend:frontend

# Run uberjar.
@run-uberjar:
    SS_DB=csv PROFILE=prod java -cp target/simpleserver.jar clojure.main -m simpleserver.core

# Lint.
@lint:
    clj -M:dev:backend:common:frontend:test -m clj-kondo.main --lint src test

# Test.
@test db:
    ./run-tests.sh {{db}}

# Clean .cpcache and .shadow-cljs directories, run npm install
@clean:
    rm -rf .cpcache/*
    rm -rf .shadow-cljs/*
    rm -rf target/*
    rm -rf dev-resources/public/js/*
    rm -rf dev-resources/public/css/*
    rm -rf prod-resources/public/js/*
    rm -rf prod-resources/public/css/*
    rm -rf dynamodb/dev-resources/*
    rm -rf out/*
    npm install
