@list:
   just --list

# Start dynamodb emulator
@dynamodb:
    cd dynamodb && ./run-docker-compose.sh

# Start backend repl.
@backend:
    clj -A:dev:scratch:test:common:backend -m nrepl.cmdline -i -C

# Lint
@lint:
   clj -A:dev -m clj-kondo.main --lint src
