@list:
   just --list

# TODO: just db which runs a docker-compose which starts both local-dynamodb and local-postgres

# Start local dynamodb emulator
@dynamodb:
    cd dynamodb && ./run-docker-compose.sh

# Start local postgres
@postgres:
    cd postgres && ./run-docker-compose.sh

# Start backend repl.
@backend:
    clj -A:dev:test:common:backend:postgres -m nrepl.cmdline -i -C

# Start backend repl with my toolbox.
@backend-kari:
    clj -A:dev:test:common:backend:postgres:kari -m nrepl.cmdline -i -C

# Lint
@lint:
    clj -A:dev -m clj-kondo.main --lint src

# Test
@test db:
    ./run-tests.sh {{db}}

